<?php

namespace Zol\Ogen\Tests\TestOpenApiServer\Api\Content;

use Zol\Ogen\Tests\TestOpenApiServer\Model\Content;
interface ContentHandler
{
    public function postContentFromPostContentApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(PostContentApplicationJsonRequestBodyPayload $requestBodyPayload): PostContent201EmptyResponse.php|PostContent400ApplicationJsonResponse.php|PostContent409ApplicationJsonResponse.php;
    public function getContentListFromEmptyPayloadToApplicationJsonContent(?string $qContentTypeId, int $qPageNumber, int $qPageSize, ?string $qSort, ?string $qStatus, ?string $qSearch): GetContentList200ApplicationJsonResponse.php;
    public function getContentFromEmptyPayloadToApplicationJsonContent(string $pContentId): GetContent200ApplicationJsonResponse.php|GetContent404ApplicationJsonResponse.php;
    public function patchContentFromPatchContentApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pContentId, PatchContentApplicationJsonRequestBodyPayload $requestBodyPayload): PatchContent200EmptyResponse.php|PatchContent400ApplicationJsonResponse.php|PatchContent404ApplicationJsonResponse.php|PatchContent409ApplicationJsonResponse.php;
    public function archiveContentFromArchiveContentApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pContentId, ArchiveContentApplicationJsonRequestBodyPayload $requestBodyPayload): ArchiveContent200EmptyResponse.php|ArchiveContent400ApplicationJsonResponse.php|ArchiveContent404ApplicationJsonResponse.php|ArchiveContent409ApplicationJsonResponse.php;
    public function restoreContentFromRestoreContentApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pContentId, RestoreContentApplicationJsonRequestBodyPayload $requestBodyPayload): RestoreContent200EmptyResponse.php|RestoreContent400ApplicationJsonResponse.php|RestoreContent404ApplicationJsonResponse.php|RestoreContent409ApplicationJsonResponse.php;
    public function duplicateContentFromEmptyPayloadToApplicationJsonContent(string $pContentId): DuplicateContent201EmptyResponse.php|DuplicateContent400ApplicationJsonResponse.php|DuplicateContent404ApplicationJsonResponse.php;
}