default:
  image: php:$PHP_VERSION-fpm
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - php composer.phar update $COMPOSER_OPTIONS

php-cs-fixer-check:
  parallel:
    matrix:
      - PHP_VERSION: ['8.3']
        COMPOSER_OPTIONS: ['']
  script:
    - php vendor/bin/php-cs-fixer -vv fix --dry-run --diff

phpstan:
  parallel:
    matrix:
      - PHP_VERSION: ['8.1', '8.2', '8.3']
        COMPOSER_OPTIONS: ['', '--prefer-lowest --prefer-stable']
  script:
    - ./ogen generate-bundle TestOpenApiServer Zol\\Ogen\\Tests\\TestOpenApiServer zol/test-openapi-server tests/openapi.yaml tests/bundle
    - php vendor/bin/phpstan analyse --memory-limit 1G --no-progress --error-format gitlab
    - php vendor/bin/phpstan analyse --memory-limit 1G --no-progress --error-format gitlab -c phpstan-bundle.neon

tests:
  parallel:
    matrix:
      - PHP_VERSION: ['8.1', '8.2', '8.3']
        COMPOSER_OPTIONS: ['', '--prefer-lowest --prefer-stable']
  script:
    - ./ogen generate-bundle TestOpenApiServer Zol\\Ogen\\Tests\\TestOpenApiServer zol/test-openapi-server tests/openapi.yaml tests/bundle
    - php vendor/bin/phpunit


deploy:
  before_script: []
  image: curlimages/curl:latest
  script:
    - 'curl --fail-with-body --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production
  only:
    - tags