build-job:
  parallel:
    matrix:
      - PHP_VERSION: ['8.1', '8.2']
  image: php:$PHP_VERSION-fpm
  script:
    - apt-get update
    - apt-get install -y zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - ./ogen TestOpenApiServer Zol\\Ogen\\Tests\\TestOpenApiServer zol/test-openapi-server tests/openapi.yaml tests/bundle
    - php vendor/bin/phpunit