#!/usr/bin/env php
<?php

error_reporting(-1);
ini_set('display_errors', 1);

use Symfony\Component\Console\Application;
use Zol\Apifony\GenerateBundleCommand;

$autoloadLocations = [
   __DIR__.'/../autoload.php',
   __DIR__.'/../../autoload.php',
   __DIR__.'/vendor/autoload.php',
];

foreach ($autoloadLocations as $autoloadLocation) {
    if (file_exists($autoloadLocation)) {
        require $autoloadLocation;
        break;
    }
}

$application = new Application();

$application->addCommands([new GenerateBundleCommand()]);

try {
    $application->run();
} catch (\Exception $e) {
    throw new \RuntimeException($e->getMessage());
}