#!/usr/bin/env php
<?php

error_reporting(-1);
ini_set('display_errors', 1);

use Zol\Ogen\Bundle\Exception as BundleException;
use Zol\Ogen\Ogen;
use Zol\Ogen\OpenApi\Exception as OpenApiException;

$autoloadLocations = [
   __DIR__.'/../autoload.php',
   __DIR__.'/../../autoload.php',
   __DIR__.'/vendor/autoload.php',
];

foreach ($autoloadLocations as $autoloadLocation) {
    if (file_exists($autoloadLocation)) {
        require $autoloadLocation;
        break;
    }
}

try {
    (new Ogen())->generate($argv[1], $argv[2], $argv[3], $argv[4], $argv[5]);
} catch (BundleException|OpenApiException $e) {
    throw new RuntimeException($e->getMessage(), 0, $e);
}

return 0;