app_zol_invoicing_presentation_api_bundle_get_client:
    path: /client/{clientId}/{param1}/{param2}/{param3}/{param4}/{param5}
    requirements:
        clientId: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
        param3: '-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?'
        param4: '-?(0|[1-9]\d*)'
        param5: 'true|false'
        param1: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
        param2: 'item'
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Default\DefaultController::getClient

app_zol_invoicing_presentation_api_bundle_post_client_client_id_param1_param2_param3_param4_param5_param6:
    path: /client/{clientId}/{param1}/{param2}/{param3}/{param4}/{param5}
    requirements:
        clientId: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
        param3: '-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?'
        param4: '-?(0|[1-9]\d*)'
        param5: 'true|false'
        param1: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
        param2: 'item'
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Default\DefaultController::postClientClientIdParam1Param2Param3Param4Param5Param6

app_zol_invoicing_presentation_api_bundle_post_test:
    path: /test/{p1}/{p2}/{p3}/{p4}
    requirements:
        p1: '[a-z]{3}'
        p2: '-?(0|[1-9]\d*)'
        p3: '-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?'
        p4: 'true|false'
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Default\DefaultController::postTest

app_zol_invoicing_presentation_api_bundle_update_pet:
    path: /pet
    methods: put
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::updatePet

app_zol_invoicing_presentation_api_bundle_add_pet:
    path: /pet
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::addPet

app_zol_invoicing_presentation_api_bundle_find_pets_by_status:
    path: /pet/findByStatus
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::findPetsByStatus

app_zol_invoicing_presentation_api_bundle_find_pets_by_tags:
    path: /pet/findByTags
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::findPetsByTags

app_zol_invoicing_presentation_api_bundle_get_pet_by_id:
    path: /pet/{petId}
    requirements:
        petId: '-?(0|[1-9]\d*)'
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::getPetById

app_zol_invoicing_presentation_api_bundle_update_pet_with_form:
    path: /pet/{petId}
    requirements:
        petId: '-?(0|[1-9]\d*)'
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::updatePetWithForm

app_zol_invoicing_presentation_api_bundle_delete_pet:
    path: /pet/{petId}
    requirements:
        petId: '-?(0|[1-9]\d*)'
    methods: delete
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::deletePet

app_zol_invoicing_presentation_api_bundle_upload_file:
    path: /pet/{petId}/uploadImage
    requirements:
        petId: '-?(0|[1-9]\d*)'
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Pet\PetController::uploadFile

app_zol_invoicing_presentation_api_bundle_get_inventory:
    path: /store/inventory
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Store\StoreController::getInventory

app_zol_invoicing_presentation_api_bundle_place_order:
    path: /store/order
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Store\StoreController::placeOrder

app_zol_invoicing_presentation_api_bundle_get_order_by_id:
    path: /store/order/{orderId}
    requirements:
        orderId: '-?(0|[1-9]\d*)'
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Store\StoreController::getOrderById

app_zol_invoicing_presentation_api_bundle_delete_order:
    path: /store/order/{orderId}
    requirements:
        orderId: '-?(0|[1-9]\d*)'
    methods: delete
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\Store\StoreController::deleteOrder

app_zol_invoicing_presentation_api_bundle_create_user:
    path: /user
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::createUser

app_zol_invoicing_presentation_api_bundle_create_users_with_list_input:
    path: /user/createWithList
    methods: post
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::createUsersWithListInput

app_zol_invoicing_presentation_api_bundle_login_user:
    path: /user/login
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::loginUser

app_zol_invoicing_presentation_api_bundle_logout_user:
    path: /user/logout
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::logoutUser

app_zol_invoicing_presentation_api_bundle_get_user_by_name:
    path: /user/{username}
    requirements:
        username: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
    methods: get
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::getUserByName

app_zol_invoicing_presentation_api_bundle_update_user:
    path: /user/{username}
    requirements:
        username: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
    methods: put
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::updateUser

app_zol_invoicing_presentation_api_bundle_delete_user:
    path: /user/{username}
    requirements:
        username: '[^:/?#[]@!$&amp;&#039;()*+,;=]+'
    methods: delete
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\Api\User\UserController::deleteUser
