app_zol_invoicing_presentation_api_bundle_get_client:
    path: /client/{clientId}/{param1}/{param2}/{param3}/{param4}/{param5}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::getClient
    requirements:
        clientId: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
        param3: '-?(0|[1-9]\\d*)(\\.\\d+)?([eE][+-]?\\d+)?'
        param4: '-?(0|[1-9]\\d*)'
        param5: 'true|false'
        param1: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
        param2: 'item'
    methods: get
    priority: 1

app_zol_invoicing_presentation_api_bundle_post_client_client_id_param1_param2_param3_param4_param5_param6:
    path: /client/{clientId}/{param1}/{param2}/{param3}/{param4}/{param5}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::postClientClientIdParam1Param2Param3Param4Param5Param6
    requirements:
        clientId: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
        param3: '-?(0|[1-9]\\d*)(\\.\\d+)?([eE][+-]?\\d+)?'
        param4: '-?(0|[1-9]\\d*)'
        param5: 'true|false'
        param1: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
        param2: 'item'
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_update_pet:
    path: /pet
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::updatePet
    methods: put
    priority: 0

app_zol_invoicing_presentation_api_bundle_add_pet:
    path: /pet
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::addPet
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_find_pets_by_status:
    path: /pet/findByStatus
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::findPetsByStatus
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_find_pets_by_tags:
    path: /pet/findByTags
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::findPetsByTags
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_get_pet_by_id:
    path: /pet/{petId}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::getPetById
    requirements:
        petId: '-?(0|[1-9]\\d*)'
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_update_pet_with_form:
    path: /pet/{petId}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::updatePetWithForm
    requirements:
        petId: '-?(0|[1-9]\\d*)'
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_delete_pet:
    path: /pet/{petId}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::deletePet
    requirements:
        petId: '-?(0|[1-9]\\d*)'
    methods: delete
    priority: 0

app_zol_invoicing_presentation_api_bundle_upload_file:
    path: /pet/{petId}/uploadImage
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::uploadFile
    requirements:
        petId: '-?(0|[1-9]\\d*)'
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_get_inventory:
    path: /store/inventory
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::getInventory
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_place_order:
    path: /store/order
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::placeOrder
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_get_order_by_id:
    path: /store/order/{orderId}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::getOrderById
    requirements:
        orderId: '-?(0|[1-9]\\d*)'
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_delete_order:
    path: /store/order/{orderId}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::deleteOrder
    requirements:
        orderId: '-?(0|[1-9]\\d*)'
    methods: delete
    priority: 0

app_zol_invoicing_presentation_api_bundle_create_user:
    path: /user
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::createUser
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_create_users_with_list_input:
    path: /user/createWithList
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::createUsersWithListInput
    methods: post
    priority: 0

app_zol_invoicing_presentation_api_bundle_login_user:
    path: /user/login
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::loginUser
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_logout_user:
    path: /user/logout
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::logoutUser
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_get_user_by_name:
    path: /user/{username}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::getUserByName
    requirements:
        username: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
    methods: get
    priority: 0

app_zol_invoicing_presentation_api_bundle_update_user:
    path: /user/{username}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::updateUser
    requirements:
        username: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
    methods: put
    priority: 0

app_zol_invoicing_presentation_api_bundle_delete_user:
    path: /user/{username}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::deleteUser
    requirements:
        username: '[^:/?#[]@!$&amp;\&#039;()*+,;=]+'
    methods: delete
    priority: 0

app_zol_invoicing_presentation_api_bundle_post_test:
    path: /test/{p1}/{p2}/{p3}/{p4}
    controller: App\Zol\Invoicing\Presentation\Api\Bundle\DefaultController::postTest
    requirements:
        p1: '[a-z]{3}'
        p2: '-?(0|[1-9]\\d*)'
        p3: '-?(0|[1-9]\\d*)(\\.\\d+)?([eE][+-]?\\d+)?'
        p4: 'true|false'
    methods: post
    priority: 0
