services:

    ### Controllers ###

    AppZolInvoicingPresentationApiBundle\Api\Default\DefaultController:
        class: AppZolInvoicingPresentationApiBundle\Api\Default\DefaultController
        arguments:
            $serializer: '@app_zol_invoicing_presentation_api_bundle.serializer_interface'
            $validator: '@validator'
        public: true

    AppZolInvoicingPresentationApiBundle\Api\Pet\PetController:
        class: AppZolInvoicingPresentationApiBundle\Api\Pet\PetController
        arguments:
            $serializer: '@app_zol_invoicing_presentation_api_bundle.serializer_interface'
            $validator: '@validator'
        public: true

    AppZolInvoicingPresentationApiBundle\Api\Store\StoreController:
        class: AppZolInvoicingPresentationApiBundle\Api\Store\StoreController
        arguments:
            $serializer: '@app_zol_invoicing_presentation_api_bundle.serializer_interface'
            $validator: '@validator'
        public: true

    AppZolInvoicingPresentationApiBundle\Api\User\UserController:
        class: AppZolInvoicingPresentationApiBundle\Api\User\UserController
        arguments:
            $serializer: '@app_zol_invoicing_presentation_api_bundle.serializer_interface'
            $validator: '@validator'
        public: true

    ### Format validators ###

    AppZolInvoicingPresentationApiBundle\Format\Int64Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\Int64Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\Int32Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\Int32Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\DateTimeValidator:
        class: AppZolInvoicingPresentationApiBundle\Format\DateTimeValidator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F21Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F21Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F22Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F22Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F23Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F23Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F25Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F25Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\FormatValidator:
        class: AppZolInvoicingPresentationApiBundle\Format\FormatValidator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F1Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F1Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F2Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F2Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F3Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F3Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F4Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F4Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F5Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F5Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F6Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F6Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F7Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F7Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F9Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F9Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F10Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F10Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F13Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F13Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F12Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F12Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F14Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F14Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F15Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F15Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F16Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F16Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F17Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F17Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F18Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F18Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F19Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F19Validator
        public: true
        tags: ['validator.constraint_validator']

    AppZolInvoicingPresentationApiBundle\Format\F20Validator:
        class: AppZolInvoicingPresentationApiBundle\Format\F20Validator
        public: true
        tags: ['validator.constraint_validator']

    ### Serializer ###

    app_zol_invoicing_presentation_api_bundle.json_encoder:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

    app_zol_invoicing_presentation_api_bundle.php_stan_extractor:
        class: 'Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor'

    app_zol_invoicing_presentation_api_bundle.reflection_extractor:
        class: 'Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor'

    app_zol_invoicing_presentation_api_bundle.property_info_extractor:
        class: 'Symfony\Component\PropertyInfo\PropertyInfoExtractor'
        arguments:
            $typeExtractors:
                - '@app_zol_invoicing_presentation_api_bundle.php_stan_extractor'
                - '@app_zol_invoicing_presentation_api_bundle.reflection_extractor'

    app_zol_invoicing_presentation_api_bundle.annotation_reader:
        class: 'Doctrine\Common\Annotations\AnnotationReader'

    app_zol_invoicing_presentation_api_bundle.annotation_loader:
        class: 'Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader'
        arguments:
            $reader: '@app_zol_invoicing_presentation_api_bundle.annotation_reader'

    app_zol_invoicing_presentation_api_bundle.class_metadata_factory:
        class: 'Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory'
        arguments:
            $loader: '@app_zol_invoicing_presentation_api_bundle.annotation_loader'

    app_zol_invoicing_presentation_api_bundle.metadata_aware_name_converter:
        class: 'Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter'
        arguments:
            $metadataFactory: '@app_zol_invoicing_presentation_api_bundle.class_metadata_factory'

    app_zol_invoicing_presentation_api_bundle.object_normalizer:
        class: 'Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
        arguments:
            $propertyTypeExtractor: '@app_zol_invoicing_presentation_api_bundle.property_info_extractor'
            $classMetadataFactory: '@app_zol_invoicing_presentation_api_bundle.class_metadata_factory'
            $nameConverter: '@app_zol_invoicing_presentation_api_bundle.metadata_aware_name_converter'

    app_zol_invoicing_presentation_api_bundle.array_denormalizer:
        class: 'Symfony\Component\Serializer\Normalizer\ArrayDenormalizer'

    app_zol_invoicing_presentation_api_bundle.serializer_interface:
        class: 'Symfony\Component\Serializer\Serializer'
        arguments:
            $encoders:
                - '@app_zol_invoicing_presentation_api_bundle.json_encoder'
            $normalizers:
                - '@app_zol_invoicing_presentation_api_bundle.object_normalizer'
                - '@app_zol_invoicing_presentation_api_bundle.array_denormalizer'