# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Validator\F1Definition:
        class: App\Validator\F1Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f1" }

    App\Validator\F2Definition:
        class: App\Validator\F2Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f2" }

    App\Validator\F3Definition:
        class: App\Validator\F3Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f3" }

    App\Validator\F4Definition:
        class: App\Validator\F4Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f4" }

    App\Validator\F5Definition:
        class: App\Validator\F5Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f5" }

    App\Validator\F6Definition:
        class: App\Validator\F6Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f6" }

    App\Validator\F8Definition:
        class: App\Validator\F8Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f8" }

    App\Validator\F9Definition:
        class: App\Validator\F9Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f9" }

    App\Validator\F10Definition:
        class: App\Validator\F10Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f10" }

    App\Validator\F12Definition:
        class: App\Validator\F12Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f12" }

    App\Validator\F13Definition:
        class: App\Validator\F13Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f13" }

    App\Validator\F14Definition:
        class: App\Validator\F14Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f14" }

    App\Validator\F15Definition:
        class: App\Validator\F15Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f15" }

    App\Validator\F16Definition:
        class: App\Validator\F16Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f16" }

    App\Validator\F17Definition:
        class: App\Validator\F17Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f17" }

    App\Validator\F18Definition:
        class: App\Validator\F18Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f18" }

    App\Validator\F19Definition:
        class: App\Validator\F19Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f19" }

    App\Validator\F20Definition:
        class: App\Validator\F20Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f20" }

    App\Validator\F21Definition:
        class: App\Validator\F21Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f21" }

    App\Validator\F22Definition:
        class: App\Validator\F22Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f22" }

    App\Validator\F23Definition:
        class: App\Validator\F23Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f23" }

    App\Validator\F25Definition:
        class: App\Validator\F25Definition
        tags:
            - { name: "invoicing_open_api_server.format_definition", format: "f25" }
