<?php

namespace Zol\Ogen\Tests\TestOpenApiServer\Api\Media;

use Zol\Ogen\Tests\TestOpenApiServer\Model\Media;
interface MediaHandler
{
    public function getMediaListFromEmptyPayloadToApplicationJsonContent(int $qPageNumber, int $qPageSize, ?string $qSort, ?string $qSearch, ?string $qFolderId): GetMediaList200ApplicationJsonResponse.php;
    public function postMediaFromPostMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(PostMediaApplicationJsonRequestBodyPayload $requestBodyPayload): PostMedia201EmptyResponse.php|PostMedia400ApplicationJsonResponse.php;
    public function getMediaFromEmptyPayloadToApplicationJsonContent(string $pMediaId): GetMedia200ApplicationJsonResponse.php|GetMedia404ApplicationJsonResponse.php;
    public function patchMediaFromPatchMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pMediaId, PatchMediaApplicationJsonRequestBodyPayload $requestBodyPayload): PatchMedia200EmptyResponse.php|PatchMedia400ApplicationJsonResponse.php|PatchMedia404ApplicationJsonResponse.php|PatchMedia409ApplicationJsonResponse.php;
    public function archiveMediaFromArchiveMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pMediaId, ArchiveMediaApplicationJsonRequestBodyPayload $requestBodyPayload): ArchiveMedia200EmptyResponse.php|ArchiveMedia400ApplicationJsonResponse.php|ArchiveMedia404ApplicationJsonResponse.php|ArchiveMedia409ApplicationJsonResponse.php;
}