<?php

namespace Zol\Ogen\Tests\TestOpenApiServer\Api\Media;

use Zol\Ogen\Tests\TestOpenApiServer\Model\Media;
interface MediaHandler
{
    public function getMediaListFromEmptyPayloadToApplicationJsonContent(int $qPageNumber, int $qPageSize, ?string $qSort, ?string $qSearch, ?string $qFolderId): GetMediaList200ApplicationJsonResponse;
    public function postMediaFromPostMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(PostMediaApplicationJsonRequestBodyPayload $requestBodyPayload): PostMedia201EmptyResponse|PostMedia400ApplicationJsonResponse;
    public function getMediaFromEmptyPayloadToApplicationJsonContent(string $pMediaId): GetMedia200ApplicationJsonResponse|GetMedia404ApplicationJsonResponse;
    public function patchMediaFromPatchMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pMediaId, PatchMediaApplicationJsonRequestBodyPayload $requestBodyPayload): PatchMedia200EmptyResponse|PatchMedia400ApplicationJsonResponse|PatchMedia404ApplicationJsonResponse|PatchMedia409ApplicationJsonResponse;
    public function archiveMediaFromArchiveMediaApplicationJsonRequestBodyPayloadPayloadToApplicationJsonContent(string $pMediaId, ArchiveMediaApplicationJsonRequestBodyPayload $requestBodyPayload): ArchiveMedia200EmptyResponse|ArchiveMedia400ApplicationJsonResponse|ArchiveMedia404ApplicationJsonResponse|ArchiveMedia409ApplicationJsonResponse;
}